#Patch PingIDM
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idm
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: openidm
        resources: {}
        envFrom:
        - configMapRef:
            name: idm
        - configMapRef:
            name: esv-variables
            optional: true
        - secretRef:
            name: esv-secrets
            optional: true
      initContainers:
      - name: load-config-clone
        resources: {}
      - name: filesystem-init
        resources: {}
      - name: truststore-init
        resources: {}
