apiVersion: v1
kind: ConfigMap
metadata:
  name: idm-boot-properties
data:
  boot.properties: |
    openidm.repo.host=ds-idrepo-0.ds-idrepo
    openidm.repo.port=1636
    openidm.repo.user=uid=admin
    openidm.repo.password=password
    openidm.repo.databaseName=openidm
    openidm.repo.schema=openidm

    openidm.anonymous.password=anonymous

    openidm.idpconfig.clientsecret=password

    userstore.host=ds-idrepo-0.ds-idrepo
    userstore.password=password
    userstore.port=1636
    userstore.basecontext=ou=identities

    openidm.port.http=8080
    openidm.port.https=8443
    openidm.port.mutualauth=8444

    openidm.lb.port.http=80
    openidm.ln.port.https=443
    openidm.auth.clientauthonlyports=8444

    openidm.https.keystore.cert.alias=openidm-localhost

    openidm.keystore.type=JCEKS
    openidm.truststore.type=JKS
    openidm.keystore.provider=SunJCE
    openidm.truststore.provider=SUN
    openidm.keystore.location=/var/run/secrets/idm/keystore.jceks
    openidm.truststore.location=/opt/openidm/idmtruststore

    openidm.keystore.password=changeit
    openidm.truststore.password=changeit

    openidm.prometheus.username=prometheus
    openidm.prometheus.password=prometheus
    openidm.prometheus.role=openidm-prometheus

    openidm.servlet.alias=/openidm
    openidm.servlet.upload.alias=/upload
    openidm.servlet.export.alias=/export

    openidm.config.crypto.alias=openidm-sym-default
    openidm.script.javascript.debug=transport=socket,suspend=y,address=9888,trace=true

    openidm.config.crypto.selfservice.sharedkey.alias=openidm-selfservice-key
    openidm.config.crypto.jwtsession.hmackey.alias=openidm-jwtsessionhmac-key
    openidm.config.crypto.opendj.localhost.cert=server-cert

    openidm.ssl.host.aliases=localhost=

    openidm.policy.enforcement.enabled=true

    openidm.scheduler.execute.persistent.schedules=true

    openidm.bonecp.statistics.enabled=false

    javascript.exception.debug.info=false

    openidm.external.rest.hostnameVerifier=ALLOW_ALL

    openidm.cluster.remove.offline.node.state=true

    openidm.apidescriptor.enabled=false

    openidm.workflow.enabled=true

    felix.fileinstall.enableConfigSave=true

    com.iplanet.am.cookie.name=iPlanetDirectoryPro
    com.sun.identity.auth.cookieName=AMAuthCookie

    rs.client.secret=idm-resource-server
