- op: replace
  path: /spec/rules/0/host
  value: mock.iam.example.com
- op: replace
  path: /spec/tls/0/hosts/0
  value: mock.iam.example.com
- op: replace
  path: /spec/tls/0/secretName
  value: platform-tls
- op: remove
  path: /spec/rules/0/http/paths/3
