#Patch PingAM
apiVersion: apps/v1
kind: Deployment
metadata:
  name: am
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: openam
        resources: {}
        env:
        - name: CATALINA_USER_OPTS
          value: "-Dam.server.protocol=https -Dam.server.fqdn=prod.iam.example.com -Dam.server.port=443"
      initContainers:
      - name: load-config-clone
        resources: {}
      - name: filesystem-init
        resources: {}
      - name: truststore-init
        resources: {}
