apiVersion: batch/v1
kind: Job
metadata:
  name: keystore-create
spec:
  template:
    spec:
      initContainers:
        - name: keystore-create
          image: us-docker.pkg.dev/forgeops-public/images/am:latest
          command:
            - bash
            - -c
            - |
              curl -sL https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-linux-amd64 -o /tmp/jq && chmod +x /tmp/jq && export PATH=/tmp:$PATH
              /home/forgerock/keystore-create.sh
          env:
            - name: KEYSTORE_TYPE
              value: jceks
