apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gitea-seed-configmap.yaml
  - gitea-seed-job.yaml

configMapGenerator:
  - name: gitea-seed-idm-conf
    files:
      - idm-conf/managed.json
      - idm-conf/repo.ds.json
      - idm-conf/access.json
  - name: gitea-seed-idm-script
    files:
      - idm-script/teammember.js
  - name: gitea-seed-am-conf
    files:
      - alpha-opendj.json=am-conf/realm/root-alpha/sunidentityrepositoryservice/1.0/organizationconfig/default/opendj.json
      - bravo-opendj.json=am-conf/realm/root-bravo/sunidentityrepositoryservice/1.0/organizationconfig/default/opendj.json
generatorOptions:
  disableNameSuffixHash: true
