apiVersion: v1
kind: ServiceAccount
metadata:
  name: esv-shim
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: esv-shim
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["get", "create"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: esv-shim
subjects:
  - kind: ServiceAccount
    name: esv-shim
roleRef:
  kind: Role
  name: esv-shim
  apiGroup: rbac.authorization.k8s.io
