apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - esv-shim-rbac.yaml
  - esv-shim-deployment.yaml
  - esv-shim-service.yaml
  - esv-shim-ingress.yaml
  - esv-projection-configmap.yaml
  - esv-projection-secret.yaml
